### PR TITLE
Create tests

### PR DESCRIPTION
**Pull request by MicahDShackelford**

### CODE REVIEW

**Comment by MicahDShackelford** [comment]
@zhangsw1 @Amershabou Please code review my spec.

**Comment by Amershabou** [comment]
Looks good! Did you use puppeteer with jest or planning to use?

**Comment by zhangsw1** [comment]
Looks good to me.

**Comment by MicahDShackelford** [comment]
> Looks good! Did you use puppeteer with jest or planning to use?
@Amershabou 
Puppeteer is for end to end tests, I dont have any end to ends planned at this point as the deliverable tracker is just calling for unit tests at this moment.

**Pull request merged**
